version: 2

sources:
  - name: raw_adventure_works
    database: SNOWFLAKE
    schema: raw_adventure_works
    tables:

      - name: address
        description: Address information for customers, employees, and vendors
        columns:
          - name: addressid