version: 2

sources:
  - name: raw_adventure_works
    database: FEA24_11
    schema: raw_adventure_works
    tables:

      - name: address
        description: Address information for customers, employees, and vendors
        columns:
          - name: addressid
            description: Primary key of the address table
            data_tests:
              - unique
              - not_null
          - name: city
            description: City of the address
            data_tests:
              - not_null
          - name: stateprovinceid
            description: Foreign key to the state province table
            data_tests:
              - not_null
              - relationships:
                  to: ref('stateprovince')
                  field: stateprovinceid

      - name: countryregion
        description: Country and region information
        columns:
          - name: countryregioncode
            description: Primary key for countryregion
            data_tests:
              - unique
              - not_null
          - name: name
            description: Country or region name
            data_tests:
              - not_null

      - name: stateprovince
        description: State and province information
        columns:
          - name: stateprovinceid
            description: Primary key for stateprovince records
            data_tests:
              - unique
              - not_null
          - name: stateprovincecode
            description: State or province code
            data_tests:
              - not_null
          - name: countryregioncode
            description: Foreign key to countryregion
            data_tests:
              - not_null
              - relationships:
                  to: ref('countryregion')
                  field: countryregioncode
          - name: name
            description: State or province name
            data_tests:
              - not_null
          - name: territoryid
            description: ID of the territory in which the state or province is located
            data_tests:
              - not_null
              - relationships:
                  to: ref('salesterritory')
                  field: territoryid

      - name: customer
        description: Current customer information
        columns:
          - name: customerid
            description: Primary key for customer records
            data_tests:
              - unique
              - not_null
          - name: territoryid
            description: ID of the territory in which the customer is located
            data_tests:
              - not_null
              - relationships:
                  to: ref('salesterritory')
                  field: territoryid

      - name: salesperson
        description: Sales representative current information
        columns:
          - name: businessentityid
            description: Primary key for SalesPerson records
            data_tests:
              - unique
              - not_null
              - relationships:
                  to: ref('businessentity')
                  field: businessentityid
          - name: territoryid
            description: Territory currently assigned to
            data_tests:
              - relationships:
                  to: ref('salesterritory')
                  field: territoryid
          - name: salesytd
            description: Sales total year to date
            data_tests:
              - not_null
          - name: saleslastyear
            description: Sales total of previous year
            data_tests:
              - not_null

      - name: person
        description: Individual customers, contacts, and venders
        columns:
          - name: businessentityid
            description: Primary key for person records
            data_tests:
              - unique
              - not_null
          - name: persontype
            description: Type of person
            data_tests:
              - not_null
          - name: firstname
            description: First name of the person
            data_tests:
              - not_null
          - name: lastname
            description: Last name of the person
            data_tests:
              - not_null

      - name: product
        description: Products sold or used in the manufacture of sold products
        columns:
          - name: productid
            description: Primary key for product records
            data_tests:
              - unique
              - not_null
          - name: name
            description: Name of the product
            data_tests:
              - not_null
          - name: productnumber
            description: Unique product identification number
            data_tests:
              - not_null

      - name: productcategory
        description: High-level product categorization
        columns:
          - name: productcategoryid
            description: Primary key for productcategory records
            data_tests:
              - unique
              - not_null
          - name: name
            description: Category description of the product
            data_tests:
              - not_null

      - name: productsubcategory
        description: Product subcategories
        columns:
          - name: productsubcategoryid
            description: Primary key for productsubcategory records
            data_tests:
              - unique
              - not_null
          - name: name
            description: Subcategory description of the product
            data_tests:
              - not_null

      - name: salesorderdetail
        description: Individual products associated with a specific sales order
        columns:
          - name: salesorderid
            description: Primary key for salesorderdetail records
            data_tests:
              - not_null
          - name: salesorderdetailid
            description: Primary key for salesorderdetail records
            data_tests:
              - unique
              - not_null
          - name: productid
            description: Foreign key to product
            data_tests:
              - not_null
              - relationships:
                  to: ref('product')
                  field: productid
          - name: orderqty
            description: Quantity ordered
            data_tests:
              - not_null
          - name: unitprice
            description: Selling price of a single product
            data_tests:
              - not_null
          - name: unitpricediscount
            description: Discount amount
            data_tests:
              - not_null

      - name: creditcard
        description: Customer credit card information
        columns:
          - name: creditcardid
            description: Primary key for creditcard records
            data_tests:
              - unique
              - not_null
          - name: cardtype
            description: Credit card type
            data_tests:
              - not_null

      - name: personcreditcard
        description: Cross-reference table mapping people and credit cards
        columns:
          - name: businessentityid
            description: Primary key for person records
            data_tests:
              - not_null
              - relationships:
                  to: ref('person')
                  field: businessentityid
          - name: creditcardid
            description: Foreign key to creditcard
            data_tests:
              - not_null
              - relationships:
                  to: ref('creditcard')
                  field: creditcardid

      - name: salesreason
        description: Customer purchase reasons
        columns:
          - name: salesreasonid
            description: Primary key for salesreason records
            data_tests:
              - unique
              - not_null
          - name: name
            description: Sales reason description
            data_tests:
              - not_null
          - name: reasontype
            description: Type of reason
            data_tests:
              - not_null

      - name: salesorderheadersalesreason
        description: Cross-reference table mapping sales order headers and sales reasons
        columns:
          - name: salesorderid
            description: Primary key for salesorderheadersalesreason records
            data_tests:
              - not_null
          - name: salesreasonid
            description: Foreign key to salesreason
            data_tests:
              - not_null
              - relationships:
                  to: ref('salesreason')
                  field: salesreasonid

      - name: salesorderheader
        description: General sales order information
        columns:
          - name: salesorderid
            description: Primary key for salesorderheader records
            data_tests:
              - unique
              - not_null
          - name: customerid
            description: Foreign key to customer
            data_tests:
              - not_null
              - relationships:
                  to: ref('customer')
                  field: customerid
          - name: salespersonid
            description: ID of the sales person
            data_tests:
              - relationships:
                  to: ref('person')
                  field: businessentityid
          - name: creditcardid
            description: Foreign key to creditcard
            data_tests:
              - relationships:
                  to: ref('creditcard')
                  field: creditcardid
          - name: territoryid
            description: ID of the territory in which the sale was made
            data_tests:
              - not_null
              - relationships:
                  to: ref('salesterritory')
                  field: territoryid
          - name: shiptoaddressid
            description: ID of the address to which the order was shipped
            data_tests:
              - not_null
              - relationships:
                  to: ref('address')
                  field: addressid
          - name: status
            description: Order status
            data_tests:
              - not_null
          - name: subtotal
            description: Sales subtotal
            data_tests:
              - not_null
          - name: taxamt
            description: Tax amount
            data_tests:
              - not_null
          - name: freight
            description: Shipping cost
            data_tests:
              - not_null
          - name: totaldue
            description: Total due
            data_tests:
              - not_null
          - name: orderdate
            description: Order date
            data_tests:
              - not_null
          - name: onlineorderflag
            description: Online order flag
            data_tests:
              - not_null

      - name: salesterritory
        description: Sales territory lookup table
        columns:
          - name: territoryid
            description: Primary key for SalesTerritory records
            data_tests:
              - not_null
          - name: name
            description: Sales territory description
            data_tests:
              - not_null
          - name: countryregioncode
            description: Standard country or region code
            data_tests:
              - not_null
          - name: group
            description: Geographic area to which the sales territory belongs

      - name: store
        description: Customers (resellers) of Adventure Works products
        columns:
          - name: businessentityid
            description: Primary key. Foreign key to Customer.BusinessEntityID
            data_tests:
              - unique
              - not_null
          - name: name
            description: Store name
            data_tests:
              - not_null
          - name: salespersonid
            description: ID of the sales person
            data_tests:
              - relationships:
                  to: ref('person')
                  field: businessentityid

      - name: employee
        description: Employee names, titles, and identification numbers
        columns:
          - name: businessentityid
            description: Primary key for employee records
            data_tests:
              - unique
              - not_null
          - name: jobtitle
            description: Job title of the employee
            data_tests:
              - not_null
          - name: gender
            description: Gender of the employee
            data_tests:
              - not_null